server:
  port: 7001

spring:
  application:
    name: eureka-server7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  # 不注册自己
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/  # 集群版
  server:
    enable-self-preservation: true  #自我保护机制，默认是true开启
